"""alter_fields_nullability

Revision ID: 6482f5531672
Revises: 9d1aa1c4586b
Create Date: 2023-09-24 18:19:23.394969

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6482f5531672"
down_revision: Union[str, None] = "9d1aa1c4586b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("categories", "parent_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("orders", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("products", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("users", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("products", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("orders", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("categories", "parent_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
