"""make article unique

Revision ID: a860c63f2706
Revises: 6482f5531672
Create Date: 2023-09-24 18:42:38.001744

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a860c63f2706"
down_revision: Union[str, None] = "6482f5531672"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "products", ["article"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="unique")
    # ### end Alembic commands ###
